### ISSUE TITLE
Keyczar throws an ImportError on import

### ISSUE THREAD

**Issue by CoderSear** [google/keyczar#168]
When importing Keyczar.keys into a Python script, the following ImportError is thrown: 
`from keyczar import keys
  File "/usr/local/lib/python3.4/dist-packages/keyczar/keys.py", line 50, in <module>
    import errors
ImportError: No module named 'errors'`

Operating system = Ubuntu 14.10, Python version 3.4.

**Comment by fordguo** [comment]
should use the absolute import ,any solution to fix this ?
