### ISSUE TITLE
Inconsistent git tagging (java_* vs Java_*) between releases

### ISSUE THREAD

**Issue by wsargent** [google/keyczar#176]
There is a release for it on September 6th 2015, but no git tag.  It is 1c245d193c04f2bd7a56389be03e2dcfa1362cac so I can check it out directly

```
git checkout 1c245d193c04f2bd7a56389be03e2dcfa1362cac
git tag java_release_0.71g
git push origin java_release_0.71g
```

It doesn't look like there's a way to do a PR for a git tag though.

**Comment by devinlundberg** [comment]
Looks like there is a tag for it:
https://github.com/google/keyczar/releases/tag/Java_release_0.71g

**Comment by wsargent** [comment]
![google_keyczar](https://cloud.githubusercontent.com/assets/71236/10350125/0fde4bf8-6cf7-11e5-815a-069b3b9cb794.png)

**Comment by devinlundberg** [comment]
The tag uses a capital J instead of a lowercase one. We should probably fix e and f to be consistent with other platforms and a-d and g.
