### ISSUE TITLE
Use cryptography.io instead of pycrypto / m2crypto

### ISSUE THREAD

**Issue by techtonik** [google/keyczar#178]
https://cryptography.io/en/latest/ is better supported on Python. Unlike both pycrypto and m2crypto, you can install `cryptography` on Windows without requiring C compiler.

**Comment by igor-raits** [comment]
Or pycryptodome.

**Comment by sweis** [comment]
+1 for cryptography.io

**Comment by divegeek** [comment]
Anyone care to send a pull request? :-)

**Comment by techtonik** [comment]
Not sure it worths it, because of https://github.com/google/keyczar#known-security-issues - I didn't get a chance to use it anyways. )

**Comment by divegeek** [comment]
Understood. I wish I had time to dig in and devise and implement a decent way to update the algorithms used. So much to do... sigh.
