### ISSUE TITLE
KeyczarTool still hosted on Google Code, referred to by wiki

### ISSUE THREAD

**Issue by timmc** [google/keyczar#184]
The wiki page https://github.com/google/keyczar/wiki/KeyczarTool points users to a Google Code page that just redirects back to the root of this repo.

Workaround: Directly download from https://keyczar.googlecode.com/files/KeyczarTool-0.71g-090613.jar (is there anything newer?)

**Comment by devinlundberg** [comment]
For KeyczarTool, you can get the latest version by downloading the code and building the code or you can use the older version hosted on google code that you found.

@divegeek we can upload packages (like jar files) to the tagged releases we create. Do we want to do so for the latest release (https://github.com/google/keyczar/releases)? The laptop I'm on doesn't have java but I can do this later.

**Comment by divegeek** [comment]
That's a good idea.

**Comment by karlhungus** [comment]
For others who are building this, you'll need to clone the repo (see https://github.com/google/keyczar/issues/167) and in `java/code` run `mvn package`

**Comment by timmc** [comment]
@sweis Can you please provide comment on why this issue was closed? It does not appear to be resolved.

**Comment by sweis** [comment]
The project was abandoned 2 years ago and all code was deleted.
