### ISSUE TITLE
Design document link in README.md is broken

### ISSUE THREAD

**Issue by hmartiniano** [google/keyczar#195]
The link for the design  document present in the readme file is broken.

**Comment by shreevatsar** [comment]
I came to report the same thing: the link is to http://keyczar.googlecode.com/files/keyczar05b.pdf which is down. Fortunately the Internet Archive's Wayback Machine has a copy from 2016-March-12: http://web.archive.org/web/20160312053606/https://keyczar.googlecode.com/files/keyczar05b.pdf

**Comment by shreevatsa** [comment]
I came here to report the same thing: the link is to http://keyczar.googlecode.com/files/keyczar05b.pdf which is down. Fortunately the Internet Archive's Wayback Machine has a copy from 2016-March-12: http://web.archive.org/web/20160312053606/https://keyczar.googlecode.com/files/keyczar05b.pdf

**Comment by asacamano** [comment]
Thanks for pointing this out - I've just updated the link.
