### ISSUE TITLE
Problem with python 3.5 

### ISSUE THREAD

**Issue by dachulin** [google/keyczar#201]
Wondering if keyczar supports python 3? Got the following error when try to import:

>>> from keyczar import keyczar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dachulin/.pyenv/versions/3.5.2/lib/python3.5/site-packages/keyczar/keyczar.py", line 26, in <module>
    import errors
ImportError: No module named 'errors'

Python2.7 works fine.

**Comment by asacamano** [comment]
My python-fu is very weak so I can't comment on the specifics.

But I would be happy to provide moral support, run tests, and review pull requests if you wanted to dive into fixing any incompatibilities.

**Comment by kamotos** [comment]
@dachulin That's probably because keyczar isn't python 3 compatible. That import line should have been `import .errors`. Will try to do a PR if I can

**Comment by ba1dr** [comment]
Voting up for this issue!

**Comment by apotapov** [comment]
+1 Any status update on this?

**Comment by Sakthivel-Eka** [comment]
Why is this issue still not solved!!

**Comment by alex20465** [comment]
I also have the same issue with python 3.6

**Comment by divegeek** [comment]
Python3 is not supported... and neither is Keyczar.  I recommend Tink.

**Comment by AmerAnsari** [comment]
I still have this problem with python3.8, how to solve it?
