### ISSUE TITLE
Java: Make ImportedKeyReader constructors public

### ISSUE THREAD

**Issue by domdorn** [google/keyczar#207]
I'm trying to migrate some crypto-code in my PlayFramework-App to Keyczar. 
Secrets/keys are handled in Play with configration files and can be overridden with environment variables. Play uses a "Application Secret" to encrypt its stuff. 

Because my app is deployed to different stages (dev/stage/preview/prod) I have different keys for all those stages. Those keys are not shipped with the app itself, but are overridden, depending on the stage through Play's Configuration mechanism. 

What that means is, that I don't have the Keys in some files conforming to Keyczar's key format, but in memory, as a String. 

To be able to use those keys, I need to use ImportedKeyReader to create a KeyReader for the Signer to work. Unfortunatelly, ImportedKeyReader is package-scoped at the moment. I had to create some hacks to be able to use it. The easiest way would be to make its constructors public or provide a way on how to construct a KeyReader with values in memory. 

`
 package org.keyczar;

 import org.keyczar.interfaces.KeyczarReader;

 public final class KeyczarHelper {

    public static KeyczarReader createImportedKeyReader(HmacKey hmacKey) {
        return new ImportedKeyReader(hmacKey);
    }
}`

`
        final String PLAY_SECRET_BASE64 = "OTNkYHA0R3RNL1RBYHFBYT5hZWZHM19SP0R0eldPeXJLaTl2QXdIeWBJZD46dVddRDlgU112QF1nPWhdPURXNg==";
        String keyczarKey = "{\"hmacKeyString\": \"" + PLAY_SECRET_BASE64 + "\"}";

        HmacKey key = new HmacKey(keyczarKey.getBytes());
        KeyczarReader keyReader = KeyczarHelper.createImportedKeyReader(key);
        Signer signer = new Signer(keyReader);
        String signature = signer.sign(message);
        boolean verified = signer.verify(message, signature);
`

Besides making the constructor public.. is there anything wrong with the code, that I'm missing?

**Comment by asacamano** [comment]
I think that seems like a good plan to me.  I'd be happy to accept a pull request.
