### ISSUE TITLE
Python3 and Keyczar

### ISSUE THREAD

**Issue by durnote** [google/keyczar#214]
Keyczar installs normally on Python3:
pip3 install python-keyczar

But I am getting this error when try to use it:
ImportError: No module named 'errors'

Just checking if Python3 is supported or not?

My system:
Ubuntu 16.04.4 LTS
python-keyczar (0.716)
Python 3.5.2

**Comment by roaldnefs** [comment]
@durnote you might want to read the following issues:

- https://github.com/google/keyczar/issues/213 Migration path from Keyczar to a Python 3 compatible library.
- https://github.com/google/keyczar/issues/125 Errors installing and ImportError while initializing on Python 3

**Comment by AmerAnsari** [comment]
Same issue with python 3.8

Is there any solvation?

**Comment by roaldnefs** [comment]
@AmerAnsari, the keyczar library isn't Python 3 compatible. Besides the Keyczar library is deprecated, you are therefore heavily advices to use another library. The Keyczar developers recommend [Tink](https://github.com/google/tink).
